In [1]:
import tsv_to_pandas

In [2]:
import urllib.request
import gzip

eurostat_link = "http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2Fisoc_sk_dskl_i.tsv.gz"
urllib.request.urlretrieve(eurostat_link , "isoc_sk_dskl_i.tsv.gz")

('isoc_sk_dskl_i.tsv.gz', <http.client.HTTPMessage at 0x7fad4a7657b8>)

In [3]:
d_skills = tsv_to_pandas.tsv_to_dataframe_long('isoc_sk_dskl_i.tsv.gz')
d_skills

,var_indic_is,var_ind_type,var_unit,var_geo,variable,value,value_raw,eurostat_annotation
0,I_DSK_AB,CB_EU_FOR,PC_IND,AT,2017,45.0,45,
1,I_DSK_AB,CB_EU_FOR,PC_IND,BE,2017,33.0,33,
2,I_DSK_AB,CB_EU_FOR,PC_IND,BG,2017,30.0,30 u,u
3,I_DSK_AB,CB_EU_FOR,PC_IND,CH,2017,43.0,43 b,b
4,I_DSK_AB,CB_EU_FOR,PC_IND,CY,2017,17.0,17,
5,I_DSK_AB,CB_EU_FOR,PC_IND,CZ,2017,30.0,30,
6,I_DSK_AB,CB_EU_FOR,PC_IND,DE,2017,28.0,28,
7,I_DSK_AB,CB_EU_FOR,PC_IND,DK,2017,39.0,39,
8,I_DSK_AB,CB_EU_FOR,PC_IND,EA,2017,27.0,27,
9,I_DSK_AB,CB_EU_FOR,PC_IND,EE,2017,31.0,31 u,u
10,I_DSK_AB,CB_EU_FOR,PC_IND,EL,2017,29.0,29,
11,I_DSK_AB,CB_EU_FOR,PC_IND,ES,2017,29.0,29,
12,I_DSK_AB,CB_EU_FOR,PC_IND,EU15,2017,29.0,29,
13,I_DSK_AB,CB_EU_FOR,PC_IND,EU27,2017,29.0,29,
14,I_DSK_AB,CB_EU_FOR,PC_IND,EU28,2017,29.0,29,
15,I_DSK_AB,CB_EU_FOR,PC_IND,FI,2017,26.0,26 u,u
16,I_DSK_AB,CB_EU_FOR,PC_IND,FR,2017,17.0,17,
17,I_DSK_AB,CB_EU_FOR,PC_IND,HR,2017,16.0,16,
18,I_DSK_AB,CB_EU_FOR,PC_IND,HU,2017,17.0,17,
19,I_DSK_AB,CB_EU_FOR,PC_IND,IE,2017,30.0,30,
20,I_DSK_AB,CB_EU_FOR,PC_IND,IS,2017,56.0,56,
21,I_DSK_AB,CB_EU_FOR,PC_IND,IT,2017,NaN,: u,u
22,I_DSK_AB,CB_EU_FOR,PC_IND,LT,2017,23.0,23 u,u
23,I_DSK_AB,CB_EU_FOR,PC_IND,LU,2017,48.0,48,
24,I_DSK_AB,CB_EU_FOR,PC_IND,LV,2017,15.0,15,
25,I_DSK_AB,CB_EU_FOR,PC_IND,MK,2017,NaN,: u,u
26,I_DSK_AB,CB_EU_FOR,PC_IND,MT,2017,63.0,63 u,u
27,I_DSK_AB,CB_EU_FOR,PC_IND,NL,2017,60.0,60,
28,I_DSK_AB,CB_EU_FOR,PC_IND,NO,2017,47.0,47,
29,I_DSK_AB,CB_EU_FOR,PC_IND,PL,2017,NaN,: u,u
...,...,...,...,...,...,...,...,...
290034,I_DSK_X,Y65_74,PC_IND_IU3,IE,2015,3.0,3,
290035,I_DSK_X,Y65_74,PC_IND_IU3,IS,2015,NaN,:,
290036,I_DSK_X,Y65_74,PC_IND_IU3,IT,2015,5.0,5,
290037,I_DSK_X,Y65_74,PC_IND_IU3,LT,2015,2.0,2,
290038,I_DSK_X,Y65_74,PC_IND_IU3,LU,2015,2.0,2,
290039,I_DSK_X,Y65_74,PC_IND_IU3,LV,2015,3.0,3,
290040,I_DSK_X,Y65_74,PC_IND_IU3,MK,2015,0.0,0,
290041,I_DSK_X,Y65_74,PC_IND_IU3,MT,2015,4.0,4,
290042,I_DSK_X,Y65_74,PC_IND_IU3,NL,2015,1.0,1,
290043,I_DSK_X,Y65_74,PC_IND_IU3,NO,2015,1.0,1,
290044,I_DSK_X,Y65_74,PC_IND_IU3,PL,2015,5.0,5,
290045,I_DSK_X,Y65_74,PC_IND_IU3,PT,2015,7.0,7,
290046,I_DSK_X,Y65_74,PC_IND_IU3,RO,2015,NaN,:,
290047,I_DSK_X,Y65_74,PC_IND_IU3,RS,2015,3.0,3,
290048,I_DSK_X,Y65_74,PC_IND_IU3,SE,2015,2.0,2,
290049,I_DSK_X,Y65_74,PC_IND_IU3,SI,2015,3.0,3,
290050,I_DSK_X,Y65_74,PC_IND_IU3,SK,2015,0.0,0 n,n
290051,I_DSK_X,Y65_74,PC_IND_IU3,TR,2015,5.0,5,
290052,I_DSK_X,Y65_74,PC_IND_IU3,UK,2015,1.0,1,
290053,I_DSK_X,Y75_MAX,PC_IND,CZ,2015,0.0,0 n,n
290054,I_DSK_X,Y75_MAX,PC_IND,ES,2015,1.0,1,
290055,I_DSK_X,Y75_MAX,PC_IND,IT,2015,0.0,0 n,n
290056,I_DSK_X,Y75_MAX,PC_IND,MK,2015,NaN,:,
290057,I_DSK_X,Y75_MAX,PC_IND,NO,2015,5.0,5 u,u
290058,I_DSK_X,Y75_MAX,PC_IND,SK,2015,0.0,0,
290059,I_DSK_X,Y75_MAX,PC_IND_IU3,CZ,2015,4.0,4,
290060,I_DSK_X,Y75_MAX,PC_IND_IU3,ES,2015,9.0,9,
290061,I_DSK_X,Y75_MAX,PC_IND_IU3,IT,2015,7.0,7,
290062,I_DSK_X,Y75_MAX,PC_IND_IU3,NO,2015,8.0,8 u,u
290063,I_DSK_X,Y75_MAX,PC_IND_IU3,SK,2015,0.0,0 u,u

In [4]:
#Importiamo pandas e numpy
import pandas as pd
import numpy as np

In [5]:
#creiamo una lista che contenga le etichette che corrispondono ai quattro livelli di digital skills e il livello nullo
skill_levels = ['I_DSK_NA', 'I_DSK_X', 'I_DSK_L', 'I_DSK_B', 'I_DSK_AB']

In [6]:
#chiedo attraverso .loc di localizzare le righe dove, nella colonna var_indic_is, sono presenti le etichette che ci servono
d_skills.loc[d_skills['var_indic_is'].isin(skill_levels)]

,var_indic_is,var_ind_type,var_unit,var_geo,variable,value,value_raw,eurostat_annotation
0,I_DSK_AB,CB_EU_FOR,PC_IND,AT,2017,45.0,45,
1,I_DSK_AB,CB_EU_FOR,PC_IND,BE,2017,33.0,33,
2,I_DSK_AB,CB_EU_FOR,PC_IND,BG,2017,30.0,30 u,u
3,I_DSK_AB,CB_EU_FOR,PC_IND,CH,2017,43.0,43 b,b
4,I_DSK_AB,CB_EU_FOR,PC_IND,CY,2017,17.0,17,
5,I_DSK_AB,CB_EU_FOR,PC_IND,CZ,2017,30.0,30,
6,I_DSK_AB,CB_EU_FOR,PC_IND,DE,2017,28.0,28,
7,I_DSK_AB,CB_EU_FOR,PC_IND,DK,2017,39.0,39,
8,I_DSK_AB,CB_EU_FOR,PC_IND,EA,2017,27.0,27,
9,I_DSK_AB,CB_EU_FOR,PC_IND,EE,2017,31.0,31 u,u
10,I_DSK_AB,CB_EU_FOR,PC_IND,EL,2017,29.0,29,
11,I_DSK_AB,CB_EU_FOR,PC_IND,ES,2017,29.0,29,
12,I_DSK_AB,CB_EU_FOR,PC_IND,EU15,2017,29.0,29,
13,I_DSK_AB,CB_EU_FOR,PC_IND,EU27,2017,29.0,29,
14,I_DSK_AB,CB_EU_FOR,PC_IND,EU28,2017,29.0,29,
15,I_DSK_AB,CB_EU_FOR,PC_IND,FI,2017,26.0,26 u,u
16,I_DSK_AB,CB_EU_FOR,PC_IND,FR,2017,17.0,17,
17,I_DSK_AB,CB_EU_FOR,PC_IND,HR,2017,16.0,16,
18,I_DSK_AB,CB_EU_FOR,PC_IND,HU,2017,17.0,17,
19,I_DSK_AB,CB_EU_FOR,PC_IND,IE,2017,30.0,30,
20,I_DSK_AB,CB_EU_FOR,PC_IND,IS,2017,56.0,56,
21,I_DSK_AB,CB_EU_FOR,PC_IND,IT,2017,NaN,: u,u
22,I_DSK_AB,CB_EU_FOR,PC_IND,LT,2017,23.0,23 u,u
23,I_DSK_AB,CB_EU_FOR,PC_IND,LU,2017,48.0,48,
24,I_DSK_AB,CB_EU_FOR,PC_IND,LV,2017,15.0,15,
25,I_DSK_AB,CB_EU_FOR,PC_IND,MK,2017,NaN,: u,u
26,I_DSK_AB,CB_EU_FOR,PC_IND,MT,2017,63.0,63 u,u
27,I_DSK_AB,CB_EU_FOR,PC_IND,NL,2017,60.0,60,
28,I_DSK_AB,CB_EU_FOR,PC_IND,NO,2017,47.0,47,
29,I_DSK_AB,CB_EU_FOR,PC_IND,PL,2017,NaN,: u,u
...,...,...,...,...,...,...,...,...
290034,I_DSK_X,Y65_74,PC_IND_IU3,IE,2015,3.0,3,
290035,I_DSK_X,Y65_74,PC_IND_IU3,IS,2015,NaN,:,
290036,I_DSK_X,Y65_74,PC_IND_IU3,IT,2015,5.0,5,
290037,I_DSK_X,Y65_74,PC_IND_IU3,LT,2015,2.0,2,
290038,I_DSK_X,Y65_74,PC_IND_IU3,LU,2015,2.0,2,
290039,I_DSK_X,Y65_74,PC_IND_IU3,LV,2015,3.0,3,
290040,I_DSK_X,Y65_74,PC_IND_IU3,MK,2015,0.0,0,
290041,I_DSK_X,Y65_74,PC_IND_IU3,MT,2015,4.0,4,
290042,I_DSK_X,Y65_74,PC_IND_IU3,NL,2015,1.0,1,
290043,I_DSK_X,Y65_74,PC_IND_IU3,NO,2015,1.0,1,
290044,I_DSK_X,Y65_74,PC_IND_IU3,PL,2015,5.0,5,
290045,I_DSK_X,Y65_74,PC_IND_IU3,PT,2015,7.0,7,
290046,I_DSK_X,Y65_74,PC_IND_IU3,RO,2015,NaN,:,
290047,I_DSK_X,Y65_74,PC_IND_IU3,RS,2015,3.0,3,
290048,I_DSK_X,Y65_74,PC_IND_IU3,SE,2015,2.0,2,
290049,I_DSK_X,Y65_74,PC_IND_IU3,SI,2015,3.0,3,
290050,I_DSK_X,Y65_74,PC_IND_IU3,SK,2015,0.0,0 n,n
290051,I_DSK_X,Y65_74,PC_IND_IU3,TR,2015,5.0,5,
290052,I_DSK_X,Y65_74,PC_IND_IU3,UK,2015,1.0,1,
290053,I_DSK_X,Y75_MAX,PC_IND,CZ,2015,0.0,0 n,n
290054,I_DSK_X,Y75_MAX,PC_IND,ES,2015,1.0,1,
290055,I_DSK_X,Y75_MAX,PC_IND,IT,2015,0.0,0 n,n
290056,I_DSK_X,Y75_MAX,PC_IND,MK,2015,NaN,:,
290057,I_DSK_X,Y75_MAX,PC_IND,NO,2015,5.0,5 u,u
290058,I_DSK_X,Y75_MAX,PC_IND,SK,2015,0.0,0,
290059,I_DSK_X,Y75_MAX,PC_IND_IU3,CZ,2015,4.0,4,
290060,I_DSK_X,Y75_MAX,PC_IND_IU3,ES,2015,9.0,9,
290061,I_DSK_X,Y75_MAX,PC_IND_IU3,IT,2015,7.0,7,
290062,I_DSK_X,Y75_MAX,PC_IND_IU3,NO,2015,8.0,8 u,u
290063,I_DSK_X,Y75_MAX,PC_IND_IU3,SK,2015,0.0,0 u,u

In [7]:
#salvo una copia di backup del database completo
d_skills_backup = d_skills

In [8]:
#salvo il database d'interesse come d_skills
d_skills = d_skills.loc[d_skills['var_indic_is'].isin(skill_levels)]

In [9]:
#Adesso salvo come d_skills soltanto la parte della matrice riguardante tutti gli individui.
d_skills = d_skills.loc[d_skills['var_ind_type'] == 'IND_TOTAL']

In [10]:
#Divido la matrice in due matrici: una con coloro che hanno usato internet negli ultimi 3 mesi, una con tutti.
d_skills_3_months = d_skills.loc[d_skills['var_unit'] == 'PC_IND_IU3']
d_skills_all = d_skills.loc[d_skills['var_unit'] == 'PC_IND']

In [15]:
#Controllo che nella matrice a 3 mesi non ci siano quelli che non hanno usato internet negli ultimi 3 mesi
d_skills_3_months.loc[d_skills['var_indic_is'] == 'I_DSK_NA']

Empty DataFrame
Columns: [var_indic_is, var_ind_type, var_unit, var_geo, variable, value, value_raw, eurostat_annotation]
Index: []

In [16]:
#Creiamo una lista con le etichette relative ai paesi che ci servono
country_list = ['IT', 'EU28', 'EU15', 'PT', 'DE']

In [18]:
#Creo una nuova matrice filtrata sulla base delle etichette in country_list. Conterrò solo i valori dei paesi di interesse
country_filter = d_skills_all.loc[d_skills_all['var_geo'].isin(country_list)]
country_filter

,var_indic_is,var_ind_type,var_unit,var_geo,variable,value,value_raw,eurostat_annotation
2467,I_DSK_AB,IND_TOTAL,PC_IND,DE,2017,37.0,37,
2473,I_DSK_AB,IND_TOTAL,PC_IND,EU15,2017,34.0,34,
2475,I_DSK_AB,IND_TOTAL,PC_IND,EU28,2017,31.0,31,
2482,I_DSK_AB,IND_TOTAL,PC_IND,IT,2017,NaN,: u,u
2492,I_DSK_AB,IND_TOTAL,PC_IND,PT,2017,31.0,31,
9145,I_DSK_B,IND_TOTAL,PC_IND,DE,2017,31.0,31,
9151,I_DSK_B,IND_TOTAL,PC_IND,EU15,2017,26.0,26,
9153,I_DSK_B,IND_TOTAL,PC_IND,EU28,2017,26.0,26,
9160,I_DSK_B,IND_TOTAL,PC_IND,IT,2017,NaN,: u,u
9170,I_DSK_B,IND_TOTAL,PC_IND,PT,2017,20.0,20,
49213,I_DSK_L,IND_TOTAL,PC_IND,DE,2017,22.0,22,
49219,I_DSK_L,IND_TOTAL,PC_IND,EU15,2017,25.0,25,
49221,I_DSK_L,IND_TOTAL,PC_IND,EU28,2017,26.0,26,
49228,I_DSK_L,IND_TOTAL,PC_IND,IT,2017,NaN,: u,u
49238,I_DSK_L,IND_TOTAL,PC_IND,PT,2017,23.0,23,
54661,I_DSK_NA,IND_TOTAL,PC_IND,DE,2017,10.0,10,
54667,I_DSK_NA,IND_TOTAL,PC_IND,EU15,2017,14.0,14,
54669,I_DSK_NA,IND_TOTAL,PC_IND,EU28,2017,16.0,16,
54676,I_DSK_NA,IND_TOTAL,PC_IND,IT,2017,29.0,29,
54686,I_DSK_NA,IND_TOTAL,PC_IND,PT,2017,26.0,26,
92573,I_DSK_X,IND_TOTAL,PC_IND,DE,2017,0.0,0 n,n
92579,I_DSK_X,IND_TOTAL,PC_IND,EU15,2017,1.0,1,
92581,I_DSK_X,IND_TOTAL,PC_IND,EU28,2017,1.0,1,
92588,I_DSK_X,IND_TOTAL,PC_IND,IT,2017,NaN,: u,u
92597,I_DSK_X,IND_TOTAL,PC_IND,PT,2017,1.0,1,
99155,I_DSK_AB,IND_TOTAL,PC_IND,DE,2016,33.0,33,
99161,I_DSK_AB,IND_TOTAL,PC_IND,EU15,2016,32.0,32,
99163,I_DSK_AB,IND_TOTAL,PC_IND,EU28,2016,29.0,29,
99170,I_DSK_AB,IND_TOTAL,PC_IND,IT,2016,19.0,19,
99180,I_DSK_AB,IND_TOTAL,PC_IND,PT,2016,28.0,28,
...,...,...,...,...,...,...,...,...
189261,I_DSK_X,IND_TOTAL,PC_IND,DE,2016,0.0,0 n,n
189267,I_DSK_X,IND_TOTAL,PC_IND,EU15,2016,1.0,1,
189269,I_DSK_X,IND_TOTAL,PC_IND,EU28,2016,1.0,1,
189276,I_DSK_X,IND_TOTAL,PC_IND,IT,2016,2.0,2,
189285,I_DSK_X,IND_TOTAL,PC_IND,PT,2016,1.0,1,
195843,I_DSK_AB,IND_TOTAL,PC_IND,DE,2015,35.0,35,
195849,I_DSK_AB,IND_TOTAL,PC_IND,EU15,2015,31.0,31,
195851,I_DSK_AB,IND_TOTAL,PC_IND,EU28,2015,28.0,28,
195858,I_DSK_AB,IND_TOTAL,PC_IND,IT,2015,19.0,19,
195868,I_DSK_AB,IND_TOTAL,PC_IND,PT,2015,28.0,28,
202521,I_DSK_B,IND_TOTAL,PC_IND,DE,2015,31.0,31,
202527,I_DSK_B,IND_TOTAL,PC_IND,EU15,2015,28.0,28,
202529,I_DSK_B,IND_TOTAL,PC_IND,EU28,2015,27.0,27,
202536,I_DSK_B,IND_TOTAL,PC_IND,IT,2015,24.0,24,
202546,I_DSK_B,IND_TOTAL,PC_IND,PT,2015,20.0,20,
242589,I_DSK_L,IND_TOTAL,PC_IND,DE,2015,21.0,21,
242595,I_DSK_L,IND_TOTAL,PC_IND,EU15,2015,23.0,23,
242597,I_DSK_L,IND_TOTAL,PC_IND,EU28,2015,23.0,23,
242604,I_DSK_L,IND_TOTAL,PC_IND,IT,2015,21.0,21,
242614,I_DSK_L,IND_TOTAL,PC_IND,PT,2015,20.0,20,
248037,I_DSK_NA,IND_TOTAL,PC_IND,DE,2015,12.0,12,
248043,I_DSK_NA,IND_TOTAL,PC_IND,EU15,2015,17.0,17,
248045,I_DSK_NA,IND_TOTAL,PC_IND,EU28,2015,21.0,21,
248052,I_DSK_NA,IND_TOTAL,PC_IND,IT,2015,34.0,34,
248062,I_DSK_NA,IND_TOTAL,PC_IND,PT,2015,31.0,31,
285949,I_DSK_X,IND_TOTAL,PC_IND,DE,2015,0.0,0 n,n
285955,I_DSK_X,IND_TOTAL,PC_IND,EU15,2015,1.0,1,
285957,I_DSK_X,IND_TOTAL,PC_IND,EU28,2015,1.0,1,
285964,I_DSK_X,IND_TOTAL,PC_IND,IT,2015,2.0,2,
285973,I_DSK_X,IND_TOTAL,PC_IND,PT,2015,1.0,1,

In [19]:
year2016 = country_filter.loc[country_filter['variable'] == 2016]

In [20]:
year2016

,var_indic_is,var_ind_type,var_unit,var_geo,variable,value,value_raw,eurostat_annotation
99155,I_DSK_AB,IND_TOTAL,PC_IND,DE,2016,33.0,33,
99161,I_DSK_AB,IND_TOTAL,PC_IND,EU15,2016,32.0,32,
99163,I_DSK_AB,IND_TOTAL,PC_IND,EU28,2016,29.0,29,
99170,I_DSK_AB,IND_TOTAL,PC_IND,IT,2016,19.0,19,
99180,I_DSK_AB,IND_TOTAL,PC_IND,PT,2016,28.0,28,
105833,I_DSK_B,IND_TOTAL,PC_IND,DE,2016,34.0,34,
105839,I_DSK_B,IND_TOTAL,PC_IND,EU15,2016,28.0,28,
105841,I_DSK_B,IND_TOTAL,PC_IND,EU28,2016,27.0,27,
105848,I_DSK_B,IND_TOTAL,PC_IND,IT,2016,24.0,24,
105858,I_DSK_B,IND_TOTAL,PC_IND,PT,2016,19.0,19,
145901,I_DSK_L,IND_TOTAL,PC_IND,DE,2016,22.0,22,
145907,I_DSK_L,IND_TOTAL,PC_IND,EU15,2016,24.0,24,
145909,I_DSK_L,IND_TOTAL,PC_IND,EU28,2016,25.0,25,
145916,I_DSK_L,IND_TOTAL,PC_IND,IT,2016,23.0,23,
145926,I_DSK_L,IND_TOTAL,PC_IND,PT,2016,22.0,22,
151349,I_DSK_NA,IND_TOTAL,PC_IND,DE,2016,10.0,10,
151355,I_DSK_NA,IND_TOTAL,PC_IND,EU15,2016,15.0,15,
151357,I_DSK_NA,IND_TOTAL,PC_IND,EU28,2016,18.0,18,
151364,I_DSK_NA,IND_TOTAL,PC_IND,IT,2016,31.0,31,
151374,I_DSK_NA,IND_TOTAL,PC_IND,PT,2016,30.0,30,
189261,I_DSK_X,IND_TOTAL,PC_IND,DE,2016,0.0,0 n,n
189267,I_DSK_X,IND_TOTAL,PC_IND,EU15,2016,1.0,1,
189269,I_DSK_X,IND_TOTAL,PC_IND,EU28,2016,1.0,1,
189276,I_DSK_X,IND_TOTAL,PC_IND,IT,2016,2.0,2,
189285,I_DSK_X,IND_TOTAL,PC_IND,PT,2016,1.0,1,

In [25]:
#Pulisco la tabella in modo che sia di facile lettura
operational = year2016.filter(['var_indic_is','var_geo','value'], axis=1)

In [26]:
operational

       var_indic_is var_geo  value
99155      I_DSK_AB      DE   33.0
99161      I_DSK_AB    EU15   32.0
99163      I_DSK_AB    EU28   29.0
99170      I_DSK_AB      IT   19.0
99180      I_DSK_AB      PT   28.0
105833      I_DSK_B      DE   34.0
105839      I_DSK_B    EU15   28.0
105841      I_DSK_B    EU28   27.0
105848      I_DSK_B      IT   24.0
105858      I_DSK_B      PT   19.0
145901      I_DSK_L      DE   22.0
145907      I_DSK_L    EU15   24.0
145909      I_DSK_L    EU28   25.0
145916      I_DSK_L      IT   23.0
145926      I_DSK_L      PT   22.0
151349     I_DSK_NA      DE   10.0
151355     I_DSK_NA    EU15   15.0
151357     I_DSK_NA    EU28   18.0
151364     I_DSK_NA      IT   31.0
151374     I_DSK_NA      PT   30.0
189261      I_DSK_X      DE    0.0
189267      I_DSK_X    EU15    1.0
189269      I_DSK_X    EU28    1.0
189276      I_DSK_X      IT    2.0
189285      I_DSK_X      PT    1.0

In [39]:
#Riordino le colonne
operational = operational[['var_geo', 'var_indic_is', 'value']]

In [40]:
operational

       var_geo var_indic_is  value
99155       DE     I_DSK_AB   33.0
99161     EU15     I_DSK_AB   32.0
99163     EU28     I_DSK_AB   29.0
99170       IT     I_DSK_AB   19.0
99180       PT     I_DSK_AB   28.0
105833      DE      I_DSK_B   34.0
105839    EU15      I_DSK_B   28.0
105841    EU28      I_DSK_B   27.0
105848      IT      I_DSK_B   24.0
105858      PT      I_DSK_B   19.0
145901      DE      I_DSK_L   22.0
145907    EU15      I_DSK_L   24.0
145909    EU28      I_DSK_L   25.0
145916      IT      I_DSK_L   23.0
145926      PT      I_DSK_L   22.0
151349      DE     I_DSK_NA   10.0
151355    EU15     I_DSK_NA   15.0
151357    EU28     I_DSK_NA   18.0
151364      IT     I_DSK_NA   31.0
151374      PT     I_DSK_NA   30.0
189261      DE      I_DSK_X    0.0
189267    EU15      I_DSK_X    1.0
189269    EU28      I_DSK_X    1.0
189276      IT      I_DSK_X    2.0
189285      PT      I_DSK_X    1.0

In [68]:
#Faccio in modo che gli indici diventino le nazioni
operational.set_index('var_geo', inplace = True)

KeyError: 'var_geo'

In [71]:
#Rinomino le colonne
operational = operational.rename(columns={"var_indic_is": "livello abilità", "value": "%"})

In [72]:
operational

        livello abilità     %
var_geo
DE             I_DSK_AB  33.0
EU15           I_DSK_AB  32.0
EU28           I_DSK_AB  29.0
IT             I_DSK_AB  19.0
PT             I_DSK_AB  28.0
DE              I_DSK_B  34.0
EU15            I_DSK_B  28.0
EU28            I_DSK_B  27.0
IT              I_DSK_B  24.0
PT              I_DSK_B  19.0
DE              I_DSK_L  22.0
EU15            I_DSK_L  24.0
EU28            I_DSK_L  25.0
IT              I_DSK_L  23.0
PT              I_DSK_L  22.0
DE             I_DSK_NA  10.0
EU15           I_DSK_NA  15.0
EU28           I_DSK_NA  18.0
IT             I_DSK_NA  31.0
PT             I_DSK_NA  30.0
DE              I_DSK_X   0.0
EU15            I_DSK_X   1.0
EU28            I_DSK_X   1.0
IT              I_DSK_X   2.0
PT              I_DSK_X   1.0

In [73]:
#Riordino la tabella e setto alcuni dei valori (il livello delle digital skill) come delle colonne e non più delle righe.
#In questo modo ottengo una matrice "standard"
operational.pivot(columns = 'livello abilità', values='%')

livello abilità  I_DSK_AB  I_DSK_B  I_DSK_L  I_DSK_NA  I_DSK_X
var_geo
DE                   33.0     34.0     22.0      10.0      0.0
EU15                 32.0     28.0     24.0      15.0      1.0
EU28                 29.0     27.0     25.0      18.0      1.0
IT                   19.0     24.0     23.0      31.0      2.0
PT                   28.0     19.0     22.0      30.0      1.0

In [81]:
#Cambio il nome delle variabili (che ora sono le nostre colonne). Rendo così la tabella leggibile.
#Rinonino di nuovo la tabella sempre operational, così che sostituisca la precedente.
#Perdo la visualizzazione a "tabella classica", no panic, basta richiamare il pivot
operational = operational.replace({'I_DSK_AB': "Above Basic", 'I_DSK_B': "Basic", 'I_DSK_L': "Low", 'I_DSK_X': "No skills", 'I_DSK_NA': "NA"})

In [82]:
operational.pivot(columns = 'livello abilità', values='%')

livello abilità  Above Basic  Basic   Low    NA  No skills
var_geo
DE                      33.0   34.0  22.0  10.0        0.0
EU15                    32.0   28.0  24.0  15.0        1.0
EU28                    29.0   27.0  25.0  18.0        1.0
IT                      19.0   24.0  23.0  31.0        2.0
PT                      28.0   19.0  22.0  30.0        1.0